name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SSH Client
      run: sudo apt-get install openssh-client

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: root@site3746.siteasp.net
        username: site3746
        key: 7Mm?Qg%4k3X@
        script: |
          cd /var/www/html
          git pull
          dotnet publish -c Release -o /var/www/html
          sudo systemctl restart kestrel-helloapp.service
