# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore App dependencies
      run: dotnet restore

    - name: Build App
      run: dotnet build --no-restore

    - name: Publish App
      run: dotnet publish -c Release -o /my_app
    
    - name: Upload App Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my_app_artifact
        path: /my_app